version: "3.8"

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"

volumes:
  dbdata:

networks:
  default:
    external:
      name: mynetwork
